name: deploy

on:
  workflow_call:
    inputs:
      environment:
        description: The environment to target for the deployment
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_REGION: ${{ vars.DEFAULT_DO_TERRAFORM_STATE_REGION }}
  AWS_ENDPOINT_URL_S3: ${{ vars.DEFAULT_DO_TERRAFORM_STATE_ENDPOINT_URL_S3 }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - run: ./deploy.sh ${{ inputs.environment }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ENDPOINT_URL_S3: ${{ env.AWS_ENDPOINT_URL_S3 }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
